### ISSUE TITLE
THE RINGS RELAY SYSTEM IS NOT WORKING 

### ISSUE THREAD

**Issue by matesaman9910** [MR-Spagetty/AUNIS-rings-relay#3]
Hi, I have a problem the program is not working when I type the starting command the computer frizzies and when I restart the computer types that the file doesn't exist when I install like 1 minute ago I don't know what is wrong but I do see that your instructions are old to open the: /home/.shrc you need to type:  edit .shrc  and the manual is not really clear I don't know how to like set up some modem or something can you help thank you.  
![obrázek_2023-01-28_155815370](https://user-images.githubusercontent.com/100013611/215273385-0be59a53-5737-4b15-bd84-b17d701fe4b6.png)

**Comment by MR-Spagetty** [comment]
the error message you have sent an image of states you do not have a modem component (wireless network card)

**Comment by MR-Spagetty** [comment]
Also doing edit /home/.shrc is a better way to tell people what to do as they may not be in the home directory which you need to be to do it simply as edit .shrc

**Comment by MR-Spagetty** [comment]
I jist noticed that i forgot to put the part requirements in the readme i tjought i had but apparently not

**Comment by MR-Spagetty** [comment]
ok the minimum part requirements are now in the README and on the JSG discord

**Comment by matesaman9910** [comment]
thank you for solving the problem I am gonna try and do what you said thank you again

**Comment by matesaman9910** [comment]
hey i have a another problem the here is foto 
![image](https://user-images.githubusercontent.com/100013611/215316335-ca6207d1-32bd-439e-8beb-b66b8268bb90.png)
this is realy weird

**Comment by VojtechSin** [comment]
> hey i have a another problem the here is foto ![image](https://user-images.githubusercontent.com/100013611/215316335-ca6207d1-32bd-439e-8beb-b66b8268bb90.png) 
this is realy weird


![image](https://user-images.githubusercontent.com/78699120/216439043-dc577961-6db8-4a0a-8641-b6d11632f150.png)
Just read :)
(type "install" to install OpenOS)

**Comment by vagabond663** [comment]
currently i am not able to load the program. its installed correctly but will not load and gives no errors
![image](https://github.com/MR-Spagetty/AUNIS-rings-relay/assets/148015006/be56b300-de44-4fa9-befa-d470488ea211)
![image](https://github.com/MR-Spagetty/AUNIS-rings-relay/assets/148015006/6d523533-4eb8-4401-85b9-0fb0bd893ee8)
and i've used all 3 different ring transporters

**Comment by MR-Spagetty** [comment]
please do not piggyback issues, also the program has infact loaded there, when the program initially starts before any commands have been issued via modem message nothing will appear in the console
